export * from './api.service';
export * from './booking.service'
export * from './hall.service';
export * from './movie.service';
export * from './place.service';
export * from './review.service';
export * from './seance.service';
export * from './ticket.service';
export * from './user.service';
